In [180]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, f1_score
from imblearn.over_sampling import SMOTE
from collections import Counter
from sklearn.svm import SVC

In [181]:
# Membaca dataset
data = pd.read_excel("Merged-Daftar-Anak-Berdasarkan-Status-Gizi.xlsx")
data

No                NIK               Nama JK  Tgl Lahir  BB Lahir  \
0        1        5405201717   IZATUNISA HUMASAH  P 2020-05-14       3.0   
1        2        3108218940              M HERU  L 2021-08-31       3.0   
2        3        2211196508         AZZAM MIRZA  L 2019-11-22       3.0   
3        4        5006211521              AISYAH  P 2021-06-10       3.0   
4        5        1106209796     M AZZAM ALFATIH  L 2020-06-11       3.1   
...    ...                ...                ... ..        ...       ...   
8830  8831  1671215702235293      TALITA HUMAIRA  P 2023-02-17       3.1   
8831  8832  1671210705241097              AZRIEL  L 2024-05-07       3.1   
8832  8833  1671214301249081               ZAHRA  P 2024-01-03       3.1   
8833  8834  1671215106235104              DELISA  P 2023-06-11       3.1   
8834  8835  1671215702221252              MAHIRA  P 2022-02-17       3.1   

      TB Lahir     Nama Ortu              Prov        Kab/Kota  ... Tinggi  \
0           50        SAIRAN  SUMATERA SELATAN  KOTA PALEMBANG  ...  100.0   
1           50        HERMAN  SUMATERA SELATAN  KOTA PALEMBANG  ...   90.0   
2           49        NOPRAN  SUMATERA SELATAN  KOTA PALEMBANG  ...  101.0   
3           50  TEGUH WIJAYA  SUMATERA SELATAN  KOTA PALEMBANG  ...   90.0   
4           50        ALPIAN  SUMATERA SELATAN  KOTA PALEMBANG  ...   99.0   
...        ...           ...               ...             ...  ...    ...   
8830        50  siti badriah  SUMATERA SELATAN  KOTA PALEMBANG  ...   78.0   
8831        50          eros  SUMATERA SELATAN  KOTA PALEMBANG  ...   58.0   
8832        50      sulaiman  SUMATERA SELATAN  KOTA PALEMBANG  ...   65.0   
8833        50         harun  SUMATERA SELATAN  KOTA PALEMBANG  ...   77.0   
8834        50          okta  SUMATERA SELATAN  KOTA PALEMBANG  ...   87.0   

       Cara Ukur  LiLA                BB/U ZS BB/U    TB/U ZS TB/U   BB/TB  \
0        Berdiri  15.0  Berat Badan Normal   -1.28  Normal   -0.12  Normal   
1        Berdiri  13.0  Berat Badan Normal   -1.17  Normal   -0.30  Normal   
2        Berdiri  15.0  Berat Badan Normal   -0.77  Normal   -0.80  Normal   
3        Berdiri  12.0  Berat Badan Normal   -1.13  Normal   -0.37  Normal   
4        Berdiri  14.0  Berat Badan Normal   -1.28  Normal   -0.32  Normal   
...          ...   ...                 ...     ...     ...     ...     ...   
8830  Terlentang  12.0  Berat Badan Normal    0.01  Normal   -0.52  Normal   
8831  Terlentang  12.0  Berat Badan Normal   -0.81  Normal   -0.54  Normal   
8832  Terlentang  12.0  Berat Badan Normal   -0.47  Normal   -0.54  Normal   
8833  Terlentang   0.0  Berat Badan Normal    0.47  Normal    0.70  Normal   
8834  Terlentang   0.0  Berat Badan Normal   -0.53  Normal   -1.02  Normal   

     ZS BB/TB  Naik Berat Badan  
0       -1.79                 N  
1       -1.56                 T  
2       -0.43                 T  
3       -1.39                 T  
4       -1.67                 T  
...       ...               ...  
8830     0.34                 N  
8831    -0.49                 N  
8832    -0.13                 N  
8833     0.21                 N  
8834    -0.02                 N  

[8835 rows x 30 columns]

In [182]:
data['Jenis Kelamin'] = data['JK'].map({'L': 1, 'P': 0})
data

No                NIK               Nama JK  Tgl Lahir  BB Lahir  \
0        1        5405201717   IZATUNISA HUMASAH  P 2020-05-14       3.0   
1        2        3108218940              M HERU  L 2021-08-31       3.0   
2        3        2211196508         AZZAM MIRZA  L 2019-11-22       3.0   
3        4        5006211521              AISYAH  P 2021-06-10       3.0   
4        5        1106209796     M AZZAM ALFATIH  L 2020-06-11       3.1   
...    ...                ...                ... ..        ...       ...   
8830  8831  1671215702235293      TALITA HUMAIRA  P 2023-02-17       3.1   
8831  8832  1671210705241097              AZRIEL  L 2024-05-07       3.1   
8832  8833  1671214301249081               ZAHRA  P 2024-01-03       3.1   
8833  8834  1671215106235104              DELISA  P 2023-06-11       3.1   
8834  8835  1671215702221252              MAHIRA  P 2022-02-17       3.1   

      TB Lahir     Nama Ortu              Prov        Kab/Kota  ...  \
0           50        SAIRAN  SUMATERA SELATAN  KOTA PALEMBANG  ...   
1           50        HERMAN  SUMATERA SELATAN  KOTA PALEMBANG  ...   
2           49        NOPRAN  SUMATERA SELATAN  KOTA PALEMBANG  ...   
3           50  TEGUH WIJAYA  SUMATERA SELATAN  KOTA PALEMBANG  ...   
4           50        ALPIAN  SUMATERA SELATAN  KOTA PALEMBANG  ...   
...        ...           ...               ...             ...  ...   
8830        50  siti badriah  SUMATERA SELATAN  KOTA PALEMBANG  ...   
8831        50          eros  SUMATERA SELATAN  KOTA PALEMBANG  ...   
8832        50      sulaiman  SUMATERA SELATAN  KOTA PALEMBANG  ...   
8833        50         harun  SUMATERA SELATAN  KOTA PALEMBANG  ...   
8834        50          okta  SUMATERA SELATAN  KOTA PALEMBANG  ...   

       Cara Ukur  LiLA                BB/U ZS BB/U    TB/U  ZS TB/U   BB/TB  \
0        Berdiri  15.0  Berat Badan Normal   -1.28  Normal    -0.12  Normal   
1        Berdiri  13.0  Berat Badan Normal   -1.17  Normal    -0.30  Normal   
2        Berdiri  15.0  Berat Badan Normal   -0.77  Normal    -0.80  Normal   
3        Berdiri  12.0  Berat Badan Normal   -1.13  Normal    -0.37  Normal   
4        Berdiri  14.0  Berat Badan Normal   -1.28  Normal    -0.32  Normal   
...          ...   ...                 ...     ...     ...      ...     ...   
8830  Terlentang  12.0  Berat Badan Normal    0.01  Normal    -0.52  Normal   
8831  Terlentang  12.0  Berat Badan Normal   -0.81  Normal    -0.54  Normal   
8832  Terlentang  12.0  Berat Badan Normal   -0.47  Normal    -0.54  Normal   
8833  Terlentang   0.0  Berat Badan Normal    0.47  Normal     0.70  Normal   
8834  Terlentang   0.0  Berat Badan Normal   -0.53  Normal    -1.02  Normal   

     ZS BB/TB Naik Berat Badan  Jenis Kelamin  
0       -1.79                N              0  
1       -1.56                T              1  
2       -0.43                T              1  
3       -1.39                T              0  
4       -1.67                T              1  
...       ...              ...            ...  
8830     0.34                N              0  
8831    -0.49                N              1  
8832    -0.13                N              0  
8833     0.21                N              0  
8834    -0.02                N              0  

[8835 rows x 31 columns]

In [ ]:
features = ['Berat', 'Tinggi', 'TB Lahir', 'BB Lahir', 'Jenis Kelamin']

for feature in features:
    if feature == 'Jenis Kelamin':
        continue  # Skip this feature since it's categorical

    # Calculate IQR for the feature
    Q1 = data[feature].quantile(0.25)  # First quartile
    Q3 = data[feature].quantile(0.75)  # Third quartile
    IQR = Q3 - Q1                    # Interquartile range

    # Define outlier bounds
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    # Replace outliers with the median
    median_value = data[feature].median()
    data[feature] = data[feature].apply(
        lambda x: median_value if x < lower_bound or x > upper_bound else x
    )
data['Height/Age'] = data['TB/U'].apply(lambda x: 'Normal' if x in ['Normal', 'Tinggi'] else 'Stunted')

target = 'Height/Age'  # Assuming 'BB/U' is the target column
target

0       Normal
1       Normal
2       Normal
3       Normal
4       Normal
         ...  
8830       NaN
8831       NaN
8832       NaN
8833       NaN
8834       NaN
Name: Height/Age, Length: 8835, dtype: object

In [161]:
data[target] = data[target].map({'Normal': 1, 'Stunted': 0})
data[target]

0       1
1       1
2       1
3       1
4       1
       ..
8830    1
8831    1
8832    1
8833    1
8834    1
Name: Height/Age, Length: 8835, dtype: int64

In [162]:
data = data.dropna(subset=features + [target])

In [163]:
X = data[features]
y = data[target]
y

0       1
1       1
2       1
3       1
4       1
       ..
8830    1
8831    1
8832    1
8833    1
8834    1
Name: Height/Age, Length: 8835, dtype: int64

In [164]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

In [165]:
smote = SMOTE(k_neighbors=1,random_state=42)
X_train_resampled, y_train_resampled = smote.fit_resample(X_train, y_train)
print("Class distribution before SMOTE:", Counter(y))
print("Class distribution after SMOTE:", Counter(y_train_resampled))

Class distribution before SMOTE: Counter({1: 8775, 0: 60})
Class distribution after SMOTE: Counter({1: 7020, 0: 7020})


In [166]:
scaler = StandardScaler()
X_train_resampled = scaler.fit_transform(X_train_resampled)
X_test = scaler.transform(X_test)

In [167]:
# MODEL KNN
# Membuat dan melatih model KNN
knn = KNeighborsClassifier(n_neighbors=5, metric='euclidean', weights='distance')
knn.fit(X_train_resampled, y_train_resampled)
y_pred = knn.predict(X_test)

In [168]:
# MODEL SVM
svm_model_linear = SVC(kernel='linear', random_state=42)
svm_model_rbf = SVC(kernel='rbf', random_state=42)
svm_model_polynomial = SVC(kernel='poly', random_state=42)
svm_model_sigmoid = SVC(kernel='sigmoid', random_state=42)

svm_model_linear.fit(X_train_resampled, y_train_resampled)
svm_model_rbf.fit(X_train_resampled, y_train_resampled)
svm_model_polynomial.fit(X_train_resampled, y_train_resampled)
svm_model_sigmoid.fit(X_train_resampled, y_train_resampled)

y_pred_linear = svm_model_linear.predict(X_test)
y_pred_rbf = svm_model_rbf.predict(X_test)
y_pred_polynomial = svm_model_polynomial.predict(X_test)
y_pred_sigmoid = svm_model_sigmoid.predict(X_test)

In [169]:
# Assuming y_test and y_pred are defined
accuracy = accuracy_score(y_test, y_pred)
accuracy_percentage = accuracy * 100

# Calculate F1-score (use average='macro' for multiclass or 'binary' for binary classification)
f1 = f1_score(y_test, y_pred, average='macro')  # Change 'macro' to 'binary' for binary classification
f1_percentage = f1 * 100

accuracy_percentage, f1_percentage

(99.20769666100736, np.float64(64.80079681274901))

In [170]:
# Menampilkan Confusion Matrix dan Classification Report
cm = confusion_matrix(y_test, y_pred)

# Ensure the problem is binary classification (2x2 matrix)
if cm.shape == (2, 2):
    TN, FP, FN, TP = cm.ravel()
    print("Confusion Matrix:")
    print(f"TP (True Positive): {TP}")
    print(f"TN (True Negative): {TN}")
    print(f"FP (False Positive): {FP}")
    print(f"FN (False Negative): {FN}")
else:
    print("This output format is specifically for binary classification.")


print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))
print("\nClassification Report:")
print(classification_report(y_test, y_pred))


Confusion Matrix:
TP (True Positive): 1750
TN (True Negative): 3
FP (False Positive): 9
FN (False Negative): 5
Confusion Matrix:
[[   3    9]
 [   5 1750]]

Classification Report:
              precision    recall  f1-score   support

           0       0.38      0.25      0.30        12
           1       0.99      1.00      1.00      1755

    accuracy                           0.99      1767
   macro avg       0.68      0.62      0.65      1767
weighted avg       0.99      0.99      0.99      1767



In [171]:
accuracy = accuracy_score(y_test, y_pred_linear)
accuracy_percentage_Linear = accuracy * 100

# Calculate F1-score (use average='macro' for multiclass or 'binary' for binary classification)
f1 = f1_score(y_test, y_pred_linear, average='macro')  # Change 'macro' to 'binary' for binary classification
f1_percentage_Linear = f1 * 100

accuracy_percentage_Linear, f1_percentage_Linear

(49.34917940011319, np.float64(34.099831276833086))

In [172]:
print("Confusion Matrix Linear:")
print(confusion_matrix(y_test, y_pred_linear))
print("\nClassification Report Linear:")
print(classification_report(y_test, y_pred_linear))

Confusion Matrix Linear:
[[ 11   1]
 [894 861]]

Classification Report Linear:
              precision    recall  f1-score   support

           0       0.01      0.92      0.02        12
           1       1.00      0.49      0.66      1755

    accuracy                           0.49      1767
   macro avg       0.51      0.70      0.34      1767
weighted avg       0.99      0.49      0.65      1767



In [173]:
accuracy = accuracy_score(y_test, y_pred_rbf)
accuracy_percentage_RBF = accuracy * 100

# Calculate F1-score (use average='macro' for multiclass or 'binary' for binary classification)
f1 = f1_score(y_test, y_pred_rbf, average='macro')  # Change 'macro' to 'binary' for binary classification
f1_percentage_RBF = f1 * 100

accuracy_percentage_RBF, f1_percentage_RBF

(85.90831918505943, np.float64(49.55995088783649))

In [174]:
print("Confusion Matrix RBF:")
print(confusion_matrix(y_test, y_pred_rbf))
print("\nClassification Report RBF:")
print(classification_report(y_test, y_pred_rbf))

Confusion Matrix RBF:
[[   9    3]
 [ 246 1509]]

Classification Report RBF:
              precision    recall  f1-score   support

           0       0.04      0.75      0.07        12
           1       1.00      0.86      0.92      1755

    accuracy                           0.86      1767
   macro avg       0.52      0.80      0.50      1767
weighted avg       0.99      0.86      0.92      1767



In [175]:
accuracy = accuracy_score(y_test, y_pred_polynomial)
accuracy_percentage_Polynomial = accuracy * 100

# Calculate F1-score (use average='macro' for multiclass or 'binary' for binary classification)
f1 = f1_score(y_test, y_pred_polynomial, average='macro')  # Change 'macro' to 'binary' for binary classification
f1_percentage_Polynomial = f1 * 100

accuracy_percentage_Polynomial, f1_percentage_Polynomial

(74.81607243916241, np.float64(45.100814151333985))

In [176]:
print("Confusion Matrix Polynomial:")
print(confusion_matrix(y_test, y_pred_polynomial))
print("\nClassification Report Polynomial:")
print(classification_report(y_test, y_pred_polynomial))

Confusion Matrix Polynomial:
[[  11    1]
 [ 444 1311]]

Classification Report Polynomial:
              precision    recall  f1-score   support

           0       0.02      0.92      0.05        12
           1       1.00      0.75      0.85      1755

    accuracy                           0.75      1767
   macro avg       0.51      0.83      0.45      1767
weighted avg       0.99      0.75      0.85      1767



In [177]:
accuracy = accuracy_score(y_test, y_pred_sigmoid)
accuracy_percentage_Sigmoid = accuracy * 100

# Calculate F1-score (use average='macro' for multiclass or 'binary' for binary classification)
f1 = f1_score(y_test, y_pred_sigmoid, average='macro')  # Change 'macro' to 'binary' for binary classification
f1_percentage_Sigmoid = f1 * 100

accuracy_percentage_Sigmoid, f1_percentage_Sigmoid

(36.55913978494624, np.float64(27.185127703115757))

In [178]:
print("Confusion Matrix Sigmoid:")
print(confusion_matrix(y_test, y_pred_sigmoid))
print("\nClassification Report Sigmoid:")
print(classification_report(y_test, y_pred_sigmoid))

Confusion Matrix Sigmoid:
[[   6    6]
 [1115  640]]

Classification Report Sigmoid:
              precision    recall  f1-score   support

           0       0.01      0.50      0.01        12
           1       0.99      0.36      0.53      1755

    accuracy                           0.37      1767
   macro avg       0.50      0.43      0.27      1767
weighted avg       0.98      0.37      0.53      1767

